### ISSUE TITLE
Iterate for loop template in reverse order

### ISSUE THREAD

**Issue by pebly** [UnexomWid/eryn#1]
It would be nice to traverse an array in reverse items order. Introducing a new flag in the loop template, for example `reversed`, would allow the user to iterate starting from the last item to the first one.

Suggested syntax example:

```
[|@ iterator : array reversed|]
body
[|end@|]
```

**Comment by UnexomWid** [comment]
Hello. Thanks for the request, seems good. It will be implemented in a future version.
