### ISSUE TITLE
Add optional index for arrays in loop templates

### ISSUE THREAD

**Issue by UnexomWid** [UnexomWid/eryn#41]
Currently, a loop template only gives the user access to the item:

```
[|@ item : items |]
    ...
[| end |]
```

However, there are cases when the index is needed.  Therefore, something like this should be added:

```
[|@ item, index : items |]
    ...
[| end |]
```

The index should be optional.

**Comment by pebly** [comment]
🔥

**Comment by UnexomWid** [comment]
This is a good idea, but it may or may not be added in the future. Until then, I will close the issue and mark it as `on hold`.
